export const SDG_Images = [
  "/images/SDG/image 19.png",
  "/images/SDG/image 20.png",
  "/images/SDG/image 21.png",
  "/images/SDG/image 22.png",
  "/images/SDG/image 23.png",
  "/images/SDG/image 24.png",
  "/images/SDG/image 25.png",
  "/images/SDG/image 26.png",
  "/images/SDG/image 27.png",
  "/images/SDG/image 28.png",
  "/images/SDG/image 29.png",
  "/images/SDG/image 30.png",
  "/images/SDG/image 31.png",
  "/images/SDG/image 32.png",
  "/images/SDG/image 33.png",
  "/images/SDG/image 34.png",
  "/images/SDG/image 35.png",
];
